#!/usr/bin/env bash
#Installing Nginx on Ubuntu

apt-get update
apt-get install nginx -y

mkdir /var/www/html
touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
service nginx restart