#!/usr/bin/env bash
# bash script to install nginx web server & make the following configurations:
#   - Nginx should be listening on port 80
#   - Return page containing "Holberton School" when queried

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/testing
touch /etc/nginx/testing/index.html
echo "Holberton School" > /etc/nginx/testing/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/testing;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart